### ISSUE TITLE
作業進め方の基本方針を決める

### ISSUE THREAD

**Issue by komajun365** [komajun365/ac-library-python#1]
そもそも基本方針の論点を洗い出すところからスタートです。

＜github使い方・PJ進め方全体方針関連＞
・githubお作法の参考になるサイトを集めてくる
・作業用slackを立てる？
・backlogのようなタスク管理ツールまでは不要？
　→　そもそもgithubにそういった機能あるのかしら？

＜移植方針＞
・python向けかpypy向けか
　→　numpyを使えるか、が大きく異なる点。
　　　余裕があるならどっちも作ればいいと思う。
・コンテストでの使い方
　→　基本的にはクラス定義したコードをコピペして使うイメージ
・移植対象
　→　pow_modなど明らかに不要なものをより分けて、移植するものだけを選別する。
　→　移植完了後だと思うが、C++のmapみたいなもの（平衡二分木）が欲しいとか、そういうのを挙げておいてもよいと思う。
・フォルダ構成を決める
　→　基本的には本家ACL準拠でよい？

他にあったら教えてください
（issueってこういう使い方でよいのかしら？

**Comment by komajun365** [comment]
移植方針 #2 
PJ管理方法 #5 
開発方針（未）

にissue分解し、こちらはクローズする予定。

**Comment by fujitahub** [comment]
closeしてみよ
