### ISSUE TITLE
移植：modint

### ISSUE THREAD

**Issue by komajun365** [komajun365/ac-library-python#17]
modintの移植
https://github.com/atcoder/ac-library/blob/master/atcoder/modint.hpp

依存関係
#include <atcoder/internal_math>
#include <atcoder/internal_type_traits>

**Comment by komajun365** [comment]
正直言って便利さがわかっていないので、
まずだれか教えてほしいなーと思っています。

**Comment by kazuki** [comment]
Nを法とした演算を便利化＋多少の最適化をする実装ですね。AtCoderとかでこういう問題ってあるのかな？
基本的には冪乗・逆元を使うような演算が無い限りは、このようなヘルパを使わずに直接%で剰余を取る等で良いと思います。

冪乗や除算など逆元を使うような場合は少し最適化が入っていて
* 逆元計算
    * 法が素数の場合はオイラーの定理を利用した方法 (バイナリ法＋数値の桁数が限られているので速いという判断かな）
    * GCDを使う方法
* 冪乗
   * バイナリ法

dynamic_modintの方は乗算にも最適化が入っててBarrett Reductionが使えるようですね。

ただこれらの実装に基づく必要があるのかはちょっと疑問で、基本的には上記テクニックは多倍長演算(1000bitとかの整数演算)を実装する際に使われるテクニックで32bit程度の範囲ではどの程度高速になるのか（またPythonでも高速化の恩恵があるのか）は不明です…
ベンチをとって高速化のためにも実装したほうが良いとか、便利クラスとしてあったほうが良いといった判断をしたほうが良いかもですね。

それか冪乗・逆元だけ用意するとかですかね。AtCoderからの完全な移植という当初の目論見からは外れてしまいますが

**Comment by komajun365** [comment]
数え上げ系の問題で、mod1000000007やmod998244353で答えさせるケースはかなりあります。
その際逆元を使うことも多いです。

ただ、指摘あったように、都度余剰を取る方法で問題ないような気がしますね。
pythonだと元々多倍長なので、計算途中のオーバーフローに気を使う必要もないです。

逆元や冪乗の計算も、pow(x,n,mod)で十分速いです。
（逆元はpow(x,mod-2,mod)）

※二項係数を答えるクエリが飛んでくる場合に、階乗の余剰&逆元を前計算しておくテクは頻出ですが、ACLライブラリはここはカバーしてないように見えます。

**Comment by kazuki** [comment]
興味があったのでベンチ

解いた問題: https://atcoder.jp/contests/abc055/tasks/abc055_b
ベンチコード: https://gist.github.com/kazuki/608d43486f3b96166a4c523ea6586fde

```
Python 3.8.6, N=1000000
    naive: 0.08872678699844982
    const: 0.08930085999963921
  barrett: 0.313119018002908
   inline: 0.2398769870014803

pypy3.6-7.3.1, N=1000000
    naive: 0.006562390997714829
    const: 0.0035995619982713833
  barrett: 0.06506652399912127
   inline: 0.06466108400127268
```

pypyはJITするので % する値を定数化すると早くなりますね。
ただ関数の手動インライン化の効果はなさそう（JITで自動インライン化しているハズ）

Pythonだとやっぱり関数呼び出しのコストは結構高いんですね〜
ただ大量に呼び出さない限りは誤差ですが…

そして僕は組み込み関数のpowを初めて知りました…math.powしか知らなかったし、組み込み関数の方のpowはモジュロ取ってくれるんですね…

**Comment by fujitahub** [comment]
とりあえず`modint`は移植せず、modをとる場合は都度mod計算するってことで良いですかね。
