### ISSUE TITLE
移植方針を決める

### ISSUE THREAD

**Issue by komajun365** [komajun365/ac-library-python#2]
## 概要

移植にあたっての方針を決定します。

- [x] 成果物の利用イメージを決める
 コピペして使えればOK or ちゃんとimportできるパッケージにする

- [x] 言語・パッケージの依存関係などを考慮した開発前提を決める
大きく変わるポイントはnumpyを前提とするかどうか。
→　numpyを前提とした場合、pypy＆多倍長整数の恩恵にあずかれなくなります。
（ほかに気にすべきポイントあったら指摘ほしい）

- [x] 引数・戻り値の複数型の対応
 どこまで気にしないといけないのかよくわからん。
 numpy使わない場合はほとんどintにしておけばOK。
 （セグ木とか、float型を載せても動きそうですが、本家が整数しか考慮してない）

- [x] modintへの対応
 fenwicktreeなど、modintを引数にできる関数があるので、切り出して議論。
 numpy使わないなら要らなくない？
 あるいは、各関数側にmodで処理する機能を持たせればよくない？という気持ち。

- [x] 移植するライブラリの範囲の決定
 pow_mod,inv_modなどはpowで代用できるから要らないよね、といった感じで
 移植対象をクラス/関数ベースで整理する。
 →　本家にないライブラリを作りたい（平衡二部木＝C++のstd::mapなど）というのは本家移植後に考えるつもり

- [x] ライブラリのフォルダ構成
 基本的には本家ACL準拠でよい？

- [x] pythonコード規約への対応（追加）
特に関数名、変数名など、
本家を準拠するか、pythonコード規約に沿って変更するかを決めたいです。

**Comment by fujitahub** [comment]
- [x] 成果物イメージ
　import できるパッケージにしたいなぁ

- [x] 言語・パッケージ
　個人的には、まずはnumpyを使わず、pypyとpythonの両方で利用できる形で作っていく方針で良いのではと
　その後、余力があればnumpyバージョンも書く

- [x] 引数・戻り値
　intで良いと思う

- [ ] modintへの対応
　個別に考えたい

- [ ] 移植範囲
　デフォルト関数・ライブラリにあるのは不要だよね、というのは同意
　平衡二分木とかについても同意

- [x] フォルダ構成
　異論なし

issueへのコメントってこんなんでええんか？
わからん

**Comment by komajun365** [comment]
・成果物イメージ
まずはコピペ版を作って、そのあとでimportできるように整える、という作業順番でいかがでしょうか？

・modint
modの引数を与えるかどうか、で内部の処理を変える方法は提案可能です。
その思想で書いたフェニック木のコードが下記になります。
https://github.com/komajun365/ac-library-python/blob/feature/fenwicktree/atcoder/fenwicktree.py

・pythonコード規約への対応（追加）
特に関数名、変数名など、
本家を準拠するか、pythonコード規約に沿って変更するかを決めたいです。

・その他
意識あっているのでクローズします。

**Comment by komajun365** [comment]
移植範囲
- convolution
- dsu
- fenwicktree
- lazysegtree
- math
  - crt
  - floor_sum
- maxflow
- mincostflow
- scc
- segtree
- string
  - suffix_array
  - lcp_array
  - z_algorithm
- twosat

・移植しない
- math
  - pow_mod
  - inv_mod
- modint

**Comment by komajun365** [comment]
書き忘れていました
・言語・パッケージの依存関係などを考慮した開発前提を決める
→　pypy利用を意識する版は、可能な限り再帰を用いないよう修正します

**Comment by chor-nyan** [comment]
「pythonコード規約」に関してですが、個人的にはPEP8に準拠し、かつflake8等でチェックしてみたいです。(関数名、変数名をどうするかは微妙なところだと思いますが、本家に沿わなくても良いのではと思ってます)

**Comment by chor-nyan** [comment]
importできるパッケージにした場合、AtCoderのコンテストにおいてもimportして使用できるのでしょうか。それができるなら、importして使えるようにしたいです。

**Comment by komajun365** [comment]
> 「pythonコード規約」に関してですが、個人的にはPEP8に準拠し、かつflake8等でチェックしてみたいです。(関数名、変数名をどうするかは微妙なところだと思いますが、本家に沿わなくても良いのではと思ってます)

では、関数名、変数名も含めてPEP8準拠で行きましょうか。
flake8でチェックというのもOKだと思います。
（linterの話などは本当は開発方針のissueを立てて決めたい）

> importできるパッケージにした場合、AtCoderのコンテストにおいてもimportして使用できるのでしょうか。それができるなら、importして使えるようにしたいです。

Atcoderでimportするには、Atcoder社の人にライブラリとして採用されるまでいかないとダメです（たぶん）。
将来的にユーザ開発ライブラリをatcoderが取り込んでくれる可能性はありますが、
言語アップデートなどもそんに頻繁に実施されるわけではないので、
すぐには実現しないだろうなぁ、という印象です。

**Comment by fujitahub** [comment]
・移植範囲
→一旦異論なし。良い感じに完成してきたら追加するのもありかも

・modint
→下記の実装は確認した。しかしこの方法だと条件分岐と関数呼び出しの回数が増えて実行時間に影響が出るため個人的には反対。
https://github.com/komajun365/ac-library-python/blob/feature/fenwicktree/atcoder/fenwicktree.py

・コード規約
→基本的にPEP8準拠という点、異論なし。
一点事前に統一しておきたいのはクォーテションの使い方
シングルクォーテーション(')、ダブルクォーテーション(")のどちらを使用するか
個人的に普段は基本シングルクォーテーションを使い
    (ex. file = 'fenwicktree.py')
複数行のコメントアウトにはダブルクォーテーションを使う
    (ex. """ ここにコメントを書く
           この行もコメント、次の行に続いてもいいよ""")

**Comment by komajun365** [comment]
> ・移植範囲
> →一旦異論なし。良い感じに完成してきたら追加するのもありかも

では、9/19いっぱいぐらい待って異論なければクローズします。

> ・modint
> →下記の実装は確認した。しかしこの方法だと条件分岐と関数呼び出しの回数が増えて実行時間に影響が出るため個人的には反対。
> https://github.com/komajun365/ac-library-python/blob/feature/fenwicktree/atcoder/fenwicktree.py

modint用の処理の有無による差は下記です。（1回だけなので信頼性低いけど）
![image](https://user-images.githubusercontent.com/37951883/93607751-b44d4f00-fa04-11ea-8b11-2553b3b84243.png)
上（modint処理あり）：https://atcoder.jp/contests/practice2/submissions/16823670
下（modint処理なし）：https://atcoder.jp/contests/practice2/submissions/16823658

この問題だと5*10**5回関数が呼ばれてこの程度の差なので、
そこまで神経質にならなくてよいのでは？と思っています。

あるいは、内部でクラス（modありなし）を二つ定義しておいて、
インスタンス作成時に引数次第で使い分ける、みたいな実装をすれば、
毎回のif文処理を計算量から落とすことも可能です。


> ・コード規約
> →基本的にPEP8準拠という点、異論なし。
> 一点事前に統一しておきたいのはクォーテションの使い方
> シングルクォーテーション(')、ダブルクォーテーション(")のどちらを使用するか
> 個人的に普段は基本シングルクォーテーションを使い
> (ex. file = 'fenwicktree.py')
> 複数行のコメントアウトにはダブルクォーテーションを使う
> (ex. """ ここにコメントを書く
> この行もコメント、次の行に続いてもいいよ""")

クォーテーションの使い方、こだわりないので異論なしです。
（めちゃくちゃミスりそう）

**Comment by kazuki** [comment]
> numpyを前提とした場合、pypy＆多倍長整数の恩恵にあずかれなくなります。（ほかに気にすべきポイントあったら指摘ほしい）

importに時間がかかるというのがありますかね。僕のそこそこ速いPCですら

```
$ echo "import math" | time python
python  0.01s user 0.00s system 39% cpu 0.036 total
$ echo "import numpy" | time python
python  0.08s user 0.03s system 52% cpu 0.207 total
```

**Comment by komajun365** [comment]
遅くなりましたがクローズします。
