### ISSUE TITLE
移植：internal_bit.hpp

### ISSUE THREAD

**Issue by komajun365** [komajun365/ac-library-python#23]
internal_bitの移植
https://github.com/atcoder/ac-library/blob/master/atcoder/internal_bit.hpp

- ceil_pow2
- bsf

依存関係なし

internalなので、依存する関数を作成時に合わせてupdateしてもらえればいいと思います

**Comment by komajun365** [comment]
ceil_pow2、bsfに関しては標準関数＋計算テクで処理できるはずなので、作らなくてもいいのでは？と思っています。

**Comment by kazuki** [comment]
bsf とかはBinary Hacksで一時期流行ったビット演算テクで比較的頻出なので、
他のライブラリで利用する場合は用意しておいたほうが楽かも？
https://graphics.stanford.edu/~seander/bithacks.html#ZerosOnRightBinSearch 
こんな感じでいくつか高速化のテクニックもあるのでPythonでどれが適切なのか計って実装するのも良いかもですね。
(grepした感じだと convolution 内で呼び出しているようです)

ceil_pow2も便利関数ですしconvolution, lazysegtree, segtreeで呼び出しているので用意しても良いかもです。
(CPU的には剰余演算は加減乗算の10倍ぐらい遅いので、ループ＋条件分岐＋乗算＋加算のほうが早かったりするのでこういう実装になっているものと思いますし、ループで実装するとなると利用する側で毎回書くのはだるいですしね。ただPythonの場合でも剰余演算が１０倍程度遅いかどうかは未計測です）

が、C++は関数呼び出しのインライン化がコンパイル時に行われるので、小さな処理を外部関数として切り出してまとめると速度に影響することはありませんが、Pythonの場合は関数呼び出しにはコストがかかるため、
あまりにも小さな処理単位を共通関数としてまとめるのは性能上少しデメリットになってしまいます。
なのでちょっと凝った実装を外部関数として呼び出す場合の性能上のメリットが打ち消されてしまう場合もあるかも。

とりあえずは処理の共通部分はatcoderライクに外に切り出しておいて、問題が起きたら個別対応とかですかねぇ

**Comment by komajun365** [comment]
https://github.com/komajun365/ac-library-python/pull/30/files
こちらの実装確認していただくとわかりやすいのですが、
これらの関数はbit_length()関数を使うことでほぼ1行で実装できちゃいます。

いったん共通部分として外に書きましたが、
呼び出し元で1行書くだけなのでそちらで実装してもいいよなぁ、という思いでした。
