### ISSUE TITLE
試験枠組みの準備

### ISSUE THREAD

**Issue by komajun365** [komajun365/ac-library-python#27]
なのでまずは、開発に取り掛かる前に、以下の枠組みを先に準備しちゃうのが良いかと。

* pyproject.toml
* /tests フォルダにダミーUTを入れておき、UTの実行環境を整える
* GitHub Actionsを使ってflake8 + UTが回るようにする

_Originally posted by @kazuki in https://github.com/komajun365/ac-library-python/issues/6#issuecomment-696657035_

**Comment by kazuki** [comment]
* https://github.com/kazuki/ac-library-python/blob/test/.github/workflows/test.yml

    * .yaml -> .yml
    * lintのあとにテストを走らせるように修正。並走してもいいけど小規模なので直列でよいかなーと
    * 別なissueでpoetryだったきがするのでpipenvからpoetryへ

* https://github.com/kazuki/ac-library-python/blob/test/pyproject.toml

   * 追加。パッケージの情報とか依存関係を定義するファイル
   * 今回は最低限ということでlintのflake8とテストランナーのpytestのみ書いてる

* https://github.com/kazuki/ac-library-python/blob/test/tests/test_import.py

  * 追加。ダミーのテストファイル。importするテストしてる

* https://github.com/kazuki/ac-library-python/blob/test/ac_library_python/__init__.py

    * 追加。ac_library_pythonというパッケージの名前空間を作成
    * https://docs.python.org/ja/3/tutorial/modules.html#packages

* https://github.com/kazuki/ac-library-python/runs/1256538121?check_suite_focus=true

    * 実行結果。こんな感じでテストが走る。

**Comment by fujitahub** [comment]
kazukiさんの多大なるヘルプのおかげで無事理解&整備できました！ありがとうございます！

**Comment by fujitahub** [comment]
こちらは整備が完了したのでクローズします。
