### ISSUE TITLE
issueのlabelを使いこなす

### ISSUE THREAD

**Issue by komajun365** [komajun365/ac-library-python#3]
## 概要

良い感じのラベルテンプレ（＋運用方針）誰か教えて

**Comment by komajun365** [comment]
https://qiita.com/shun_tak/items/d363b7c5d9e8fa19dc6b
これがいいかなと思ってます

**Comment by kazuki** [comment]
* A-xxx: Area: 問題発生箇所
* C-xxx: Category: issueの種類. C-bug, C-enhancement, C-discussion, ...
* P-xxx: Priority: P-high, P-low とか
* S-xxx: Status. S-blocked, S-waiting-on-author, S-waiting-on-review とか
* invalid/duplicate/wontfix

ってな感じなのをよく使うかなー。単にちょっとPrefixが短いぐらいですね。
クローズの理由はprefixつけないことが多いけどこれはデフォルトで用意されているからという雑な理由だったり…

**Comment by komajun365** [comment]
kazukiさんには申し訳ないのですが、
今回はqiita記事のやつを採用してみようと思います。
やってみて困ったらまた考えます。

**Comment by komajun365** [comment]
label設定をしたのでクローズします。
