### ISSUE TITLE
PJ管理の方針を決める

### ISSUE THREAD

**Issue by komajun365** [komajun365/ac-library-python#5]
## 概要

課題・タスク管理の大雑把な方針を決めます。

### メンターさんのありがたいコメント

- issueベース。タスクはissueで管理。細かすぎるものはissueの中にチェックリストを作って管理 (チェックリストにするとgithub issuesから完了済みとかの数がわかる) 
- Projectでタスク管理できるように、ラベルを振る (個人的にはprojectは使わなくてもいいかなーと思うけどラベルは降っておいたほうが良い。issue一覧でフィルタとかできるので) 
- リリース単位のProjectとイテレーション単位のProjectがあってもよいのかも？（https://qiita.com/itkr/items/0d4c0015da28827b2bb7）
- （僕はリリース単位でマイルストーンを設定して、それを使うことが多いけど）

**Comment by komajun365** [comment]
いったんACLの移植（詳細なゴールは別途議論）までをマイルストーンとして
プロジェクトを作ります。
（休みの間に調べながらやります。）

**Comment by kazuki** [comment]
https://docs.github.com/ja/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue

pull reqをマージすると対応するissueを自動クローズすることもできますー

**Comment by komajun365** [comment]
遅くなりましたがクローズします。
