### ISSUE TITLE
開発方針を決める

### ISSUE THREAD

**Issue by chor-nyan** [komajun365/ac-library-python#6]
開発環境
- [ ] パッケージング: pyproject.toml, poetry? [参考](https://tech.515hikaru.net/post/2019-11-23-pyproject/) 
- [ ] lint: flake8 ?
- [ ] 型チェックはするか: mypy ?
- [ ] テストフレームワークは使うか（nose, unittest）

開発方針
- [x] ACLの移植に留める or 拡張する 
  - 拡張するか否かは誰が決める？

CI/CD
- [ ] CI: GitHub Actions (UTぐらいは回しておく？) [参考](https://knowledge.sakura.ad.jp/23478/) 
- [ ] CD: Tagを打ったらpypiに自動アップロードするとか

github/gitに関する参考サイト
- [A successful Git branching model](https://qiita.com/homhom44/items/9f13c646fa2619ae63d0) 
- [GitLab flowから学ぶワークフローの実践](https://postd.cc/gitlab-flow/)

**Comment by komajun365** [comment]
> 開発方針
> 
> ACLの移植に留める or 拡張する
> 拡張するか否かは誰が決める？

#2 で議論しているのでこちらからは削除してOKです。
（まずは移植完了までを実施し、完成したら拡張の議論をする、というような風潮になっています。）


- ブランチの利用ポリシーについて
Git-Flowが重いよね、というのはその通りだと思います。
あんまり複雑な運用にしてもどうなの？と思うので、
Github-Flowを採用する、に1票です。
（Gitlab-flowよりお手軽に見えるのでそう発言しているのですが、誤っていたら指摘ください）

**Comment by chor-nyan** [comment]
GitHub難しくてよく理解できていませんが、「masterからブランチを切って開発 -> プルリクエスト -> masterにmergeしてデプロイ」の流れで開発するのがGitHub-Flowって感じですかね。

**Comment by komajun365** [comment]
私もよくわかっていませんが、その認識でずれていないと思います。

ここのサイトの記述が丁寧でした。
https://thinkit.co.jp/article/8410

> GitHub Flow実践にあたっての要点は下記にまとめることができます。
> 
> - masterブランチは常に本番環境へデプロイ可能にする
> - 開発を始める際にはまずブランチを作成する(ブランチ名は内容を説明するようなものがよい)
> - 準備が整い次第できるだけ早くPull Requestを作成し、コラボレーションを始める
> - コードレビューやCIを実施しながらブランチにコミットを重ねていく
> - レビュー完了、CI通過、等々なんらかの基準を満たした後、当該ブランチをデプロイする
> - 問題が発生した場合にはmasterをデプロイし直す
> - デプロイ後問題なければ当該ブランチをmasterにマージし、当該ブランチを削除する
> 
> 特にデプロイの箇所が2011年当時とは変わっていますが（当時はmasterにマージしてからデプロイする旨記述していた）、大枠はこのようになります。

あとはこことか
https://tracpath.com/bootcamp/learning_git_github_flow.html

**Comment by motohidentaku** [comment]
開発環境ってみんな普段はどんなかんじなんだろうか？

最初の案のpoetry、flake8、mypy あたりは好みの問題が大きいけど、それでよいのかなと。って、自分がそれだからだけど。

あとは、どこまで今風の開発にするかだね。
unittest入れて、pushしたら、github側でも、CIでflake8とunittestして、結果をREADMEのバッチに表示して、Slackに通知するとかするかね。

**Comment by komajun365** [comment]
開発に関しては全く経験ないので静観していましたが、
経験者の推奨方法を学ばせてもらうのが一番かな、というのが自分の意見です。

そもそも今回テストをどのように設計するか、
みたいなところ次第で事前に準備しておくべきものの範囲も大きく変わる気がしています。

**Comment by kazuki** [comment]
> 開発環境ってみんな普段はどんなかんじなんだろうか？
> 最初の案のpoetry、flake8、mypy あたりは好みの問題が大きいけど、それでよいのかなと。って、自分がそれだからだけど。

今年度の僕は、pyenv + poetry(pyproject) + mypy + flake8(isort, quotes, docstrings) + nose2(+coverage-plugin) ですね。
(昨年度は poetry じゃなくて pipenv 使ってましたが)

> あとは、どこまで今風の開発にするかだね。

GitHub Actionsを使ったCIは設定すべきですね。PR時にもCIがパスしてないとそもそもマージ出来ないようにするとかのガードはレビュアの負担を軽減するので導入すべきですね。

バッチとかはSlackはお好みでですかね。バッチはお飾りの意味合い程度しか無い気がしているので。
開発スピードが速いときはSlack連携は便利です。issue/PRが出されたり、CIがコケると通知が着てすぐに対応できるので。

なのでまずは、開発に取り掛かる前に、以下の枠組みを先に準備しちゃうのが良いかと。

* pyproject.toml
* /tests フォルダにダミーUTを入れておき、UTの実行環境を整える
* GitHub Actionsを使ってflake8 + UTが回るようにする

**Comment by kazuki** [comment]
GitHub Actions+Pythonの参考ページ:
* https://www.lifewithpython.com/2020/04/python-github-actions.html
* https://github.com/marketplace/actions/setup-python

Pythonのパッケージ管理ソフト
* https://github.com/python-poetry/poetry 
* 従来は setup.py だったけど最近は pyproject.toml になっているらしい！

Flake8
* isort, quotes, docstrings とかはお好みで～

mypy: お好みで

nose2. ほかにもUT実行ツールはあるけど，nose2で特に困ってないかな…
* coverage-plugin: https://docs.nose2.io/en/latest/plugins/coverage.html

**Comment by komajun365** [comment]
開発方針かどうかわかりませんが、関数アノテーションとdocstringについて。
いったんの方針。

・関数アノテーション
→　場合によって複数の型を取れる可能性があるので書かない
・docstring
→　書く。Numpyスタイルで。日本語でOK。
　　https://qiita.com/simonritchie/items/49e0813508cad4876b5a
　　＜書く項目＞
　　関数／クラスの概要
　　引数・戻り値の型、制約
　　クラスの属性値

　　※ただし、細かすぎる内容は公式ドキュメント側に投げるのもあり。

**Comment by komajun365** [comment]
遅くなりましたがクローズします。
