### ISSUE TITLE
fenwicktree.pyのバグ（ついでにお作法を教えてください）

### ISSUE THREAD

**Issue by komajun365** [komajun365/ac-library-python#7]
feature/fenwicktreeブランチの下記ファイルがバグっていることがわかりました。
https://github.com/komajun365/ac-library-python/blob/feature/fenwicktree/atcoder/fenwicktree.py

45行目でreturnする前に、
% self.__modで余剰を取ってあげないといけません。

これはどのようにレビューされて修正されるべきなのでしょうか？
・pushした人（komajun365）がプルリクを送る
・コードレビューした人（komajun365以外）がbugを指摘する
・誰かが修正する？
・プルリクをクローズする
・（現時点では移植方針が未定なのでまだやらないけど、マージOKならmasterにマージする）

こんな流れでしょうか？
教えて詳しい人！

**Comment by kazuki** [comment]
運営方針によっていくつか運用ルールが異なりますが、大まかには以下のような流れになるかと。

1. バグのissueを立てる (再現方法・コード、影響範囲等を記載する)
1. (規模が大きいプロジェクトの場合は権限がある人がissueをトリアージし、アサイン先を設定する)
1. issueで必要に応じて修正方針について議論する（軽微な場合はスキップ可）
1. PRを出す
1. PRの内容をレビューしコメントする
1. PRのレビューコメントに対応する
1. PRをマージ or リジェクト(クローズ)

どのステップを誰が担当するかですが、

* 作業中ブランチの場合は、そのブランチのオーナーの裁量で。PR経由せずに直接コミットも可。
* master/developなどのブランチ、または複数人で作業するような大きめな作業ブランチの場合は、上記手順を踏んで修正する。issue/PR出す人は同じでもいいし別でも良い。レビューやマージはオーナーやそのコードのメイン作者等が実施（PR出した人とは別）

って感じですかね。

今回は作業ブランチっぽいので、そのまま修正コミットを追加して良いと思います。
issue/PRを通して修正するのはオーバーヘッドがそれなりにあるので。

**Comment by komajun365** [comment]
ありがとうございます。
では普通に修正コミット追加してクローズしちゃいますね。
